// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtub7od8TVl9VtuThahoFAM5vrXQMDXUU',
    appId: '1:350260074721:web:44d601fa22bbdea6aa3fa0',
    messagingSenderId: '350260074721',
    projectId: 'luxestore-43d3b',
    authDomain: 'luxestore-43d3b.firebaseapp.com',
    databaseURL: 'https://luxestore-43d3b-default-rtdb.firebaseio.com',
    storageBucket: 'luxestore-43d3b.firebasestorage.app',
    measurementId: 'G-B26SW3EZ88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIsf4XLu2i8EOUY3Dyfk-HDBTXy2RB8U',
    appId: '1:350260074721:android:939bdf32f2fe625baa3fa0',
    messagingSenderId: '350260074721',
    projectId: 'luxestore-43d3b',
    databaseURL: 'https://luxestore-43d3b-default-rtdb.firebaseio.com',
    storageBucket: 'luxestore-43d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiWPihP3Fr254_zmp08C-akDKDNfH0C_Q',
    appId: '1:350260074721:ios:945c10a01d535ba7aa3fa0',
    messagingSenderId: '350260074721',
    projectId: 'luxestore-43d3b',
    databaseURL: 'https://luxestore-43d3b-default-rtdb.firebaseio.com',
    storageBucket: 'luxestore-43d3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiWPihP3Fr254_zmp08C-akDKDNfH0C_Q',
    appId: '1:350260074721:ios:945c10a01d535ba7aa3fa0',
    messagingSenderId: '350260074721',
    projectId: 'luxestore-43d3b',
    databaseURL: 'https://luxestore-43d3b-default-rtdb.firebaseio.com',
    storageBucket: 'luxestore-43d3b.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtub7od8TVl9VtuThahoFAM5vrXQMDXUU',
    appId: '1:350260074721:web:4bb24e658fe38830aa3fa0',
    messagingSenderId: '350260074721',
    projectId: 'luxestore-43d3b',
    authDomain: 'luxestore-43d3b.firebaseapp.com',
    databaseURL: 'https://luxestore-43d3b-default-rtdb.firebaseio.com',
    storageBucket: 'luxestore-43d3b.firebasestorage.app',
    measurementId: 'G-G248Q1RG0S',
  );
}
